# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-MarkLogic-XDBC
version:      0.05
version_from: lib/Net/MarkLogic/XDBC.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Class::Fields:                 0
    HTTP::Headers:                 0
    LWP::UserAgent:                0
    Template:                      0
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
